.\"*****************************************************************************
.\" Copyright 1995-2004,2010 by Thomas E. Dickey.  All Rights Reserved.        *
.\"                                                                            *
.\" Permission to use, copy, modify, and distribute this software and its      *
.\" documentation for any purpose and without fee is hereby granted, provided  *
.\" that the above copyright notice appear in all copies and that both that    *
.\" copyright notice and this permission notice appear in supporting           *
.\" documentation, and that the name of the above listed copyright holder(s)   *
.\" not be used in advertising or publicity pertaining to distribution of the  *
.\" software without specific, written prior permission.                       *
.\"                                                                            *
.\" THE ABOVE LISTED COPYRIGHT HOLDER(S) DISCLAIM ALL WARRANTIES WITH REGARD   *
.\" TO THIS SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND  *
.\" FITNESS, IN NO EVENT SHALL THE ABOVE LISTED COPYRIGHT HOLDER(S) BE LIABLE  *
.\" FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES          *
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN      *
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR *
.\" IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.                *
.\"*****************************************************************************
.\" $Id: conflict.1,v 6.4 2010/06/27 19:57:28 tom Exp $
.de ES
.RS
.nf
.sp
..
.de EE
.fi
.RE
.sp .5
..
.TH CONFLICT 1
.hy 0
.
.SH NAME
\fBconflict\fR \- filename conflict listing
.
.SH SYNOPSIS
\fBconflict\fP\fI [options] [file-specifications]\fP
.
.SH DESCRIPTION
\fBConflict\fR displays conflicting filenames in your execution path.
Unlike the csh command \fIwhich\fR,
it displays all of the (non-alias) executable files in your path.
.
.PP
\fBConflict\fR reports pathname conflicts by making a list of the
directories which are listed in the environment variable PATH, and
then scanning these directories for executable files.
If arguments are given to this program,
the test for executable files is limited
to the given names (after stripping the directory-prefix).
.PP
The first instance of a name in a given path
(and those hard-linked to it) are marked with "*".
Succeeding instances are marked with "+" marks.
.PP
The report is sent to standard output and always shows the list of
directories.
Conflicting names are reported on succeeding lines.
.
.SH OPTIONS
.TP
.BI -e " name"
specify another environment variable than PATH
(e.g., INFOPATH, LD_LIBRARY_PATH).
.
.TP
.BI -I " path"
for compatibility with C-preprocessor options, build up the search path
with the given directory.
(The corresponding \fB-D\fP and \fB-U\fP options are ignored.)
Using the \fB-I\fP or \fB-L\fP options overrides the use of environment variables
for the search path.
.
.TP
.BI -L " path"
for compatibility with C-compiler options, build up the search path
with the given directory.
.
.TP
.B -p
print pathnames only, rather than the table.
.
.TP
.B -r
look for readable files
.
.TP
.BI -t " types"
specify a list of file types which are treated as conflicting.
The option value is a list of file suffixes (a "." followed by
zero or more other characters).
The list separator is the "." which begins each suffix, e.g.,
.ES
	conflict -t.exe.com
.EE
.IP
If no \fB-t\fP option is given,
a built-in list of executable file types is used for systems
where this is known.
.
.TP
.B -v
Use verbose option to control how much is shown.
Repeat the option for different levels:
.RS
.TP
.I 1
show all directory names
.TP
.I 2
show all filenames which are found in the directories
.TP
.I 3
directs \fBconflict\fR not only
to print a summary line for each file, but also to print a running
summary, showing executable file (with its full path) as it is found).
.RE
.
.TP
.B -V
print the version, exit.
.
.TP
.B -w
look for writable files
.
.TP
.BI -W " number"
expand width of display by number of columns (default: one column per path).
.
.TP
.B -x
look for executable files (the default).
.
.PP
You may combine the "\fB-r\fP", "\fB-w\fP" and "\fB-x\fP" options.
If you do not specify one of these, \fBconflict\fR assumes "\fB-x\fP".
.
.SH OPERATIONS
\fBConflict\fR may be used to list all conflicting names in your
path (if no arguments are given), or to find conflicts for a specified
name.
To list only conflicts from a particular directory "path"
you may type
.ES
conflict -a path/*
.EE
.PP
An example of the use of \fBconflict\fR is shown below
.ES
bsd4.2(5) conflict
Current working directory is "/home/dickey/src/conflict"
-> .
--> /home/dickey/bin
---> /home/dickey/com
----> /bin
-----> /usr/bin
------> /usr/ucb
-------> /usr/local/bin
-*----+: args
----*-+: calendar
---*--+: cc
*+-----: conflict
\&...
.EE
.
.SH ENVIRONMENT
\fBConflict\fR runs in a portable UNIX\*R environment, as well as
MSDOS, Win32 and OS/2 command-line.
.
.SH FILES
\fBConflict\fR is a single binary module, which uses no auxiliary files.
.
.SH ANTICIPATED CHANGES
add option to get aliases from the shell
.PP
handle compound directory structures such as MANPATH.
.PP
show symbol conflicts from object files and libraries.
.
.SH SEE ALSO
csh (1) for a discussion of \fIwhich\fR.
.
.SH AUTHOR
Thomas Dickey
